### ISSUE TITLE
Application name

### ISSUE THREAD

**Issue by burakcoskunn** [iMatthewCM/Jamf-Scripts#2]
Hello sir,
Thanks a lot for your time to add this. Could you please inform me which line for i can write app name to get full report of this app?

**Comment by iMatthewCM** [comment]
Hey @burakcoskunn,

**So** sorry for how late this reply is...TIL I had an open issue that I haven't been paying attention to!

I presume we're talking about the applicationUsageAPI.sh script? If so, there's nowhere you need to write in the app name - the script will prompt you for it. You only need to configure lines 46, 49, and 54 with your username, password, and Jamf Pro URL. All other information is acquired via prompt.

I figure in 2 years you've probably moved on to other scripts, so again, my apologies, just figured I'd respond here in case others have the same issue. Thanks!

-Matthew

**Comment by burakcoskunn** [comment]
Hello @iMatthewCM 
Thank you for your response. I figured this. Thanks a lot for you shared thşs script.
See you
